# NOTE: First database login can be done as root with no password. It is recommended to change this.

services:
  python_custom_service:
    build: 
      context: .
      dockerfile: db_attach.dockerfile
    container_name: test_container
    restart: always
    links:
      - 'db'

  db:
    image: mysql
    container_name: db
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    volumes:
      - ./pma_theme_boodark:/var/www/html/themes/boodark
    ports:
      - 8081:80